---
layout: cv
title: Rand al'Thor's CV
---

# Rand al'Thor

The Dragon Reborn, Car'a'carn.

<div id="webaddress">
<a href="rand@dragonmount.org">rand@dragonmount.org</a>  
| <a href="https://wot.fandom.com/wiki/Rand_al%27Thor">More information</a>
</div>

## Currently

Currently deceased

### Specialized in

Taking a nice peaceful setting and turning it into a mess

### Research interests

Anchient Prophecy

## Education

`~998 NE`
**A Farm, Two Rivers, Andor**

- learned basic literacy and all about being a shepherd

`999 NE - 1001 NE`
**Various institutions, Worldwide**

- Advanced degree in being the problem

## Awards

`999 NE`
Proclaimed the _Dragon Reborn_, Tier, Tier

`999 NE`
Proclaimed _He Who Comes with the Dawn_, Alcair Dal, Aiel Waste

`1001 NE`
Awarded the Laural Crown of Ilian, Ilian, Ilian

## Publications

`999 NE`

- He wrote a note to his friends when he ran away.

### Legislation

`999 NE`

- Various ammendments to the law of the Nation of Teir, expanding civil rights for peasants and imposing taxes and agressive new foreign aid policy.

### Other Works

`-inf NE - 1000 NE`  
Unwilling collaboration with Lews Therin Telamon (mental co-authorship).

## Occupation

`998 – 1001 NE`  
**Mess Maker**, World-wide

- Made a mess in **Shienar** and the lands formerly claimed by **Malkier** by confronting two resurrected Forsaken
- Made a large mess in **Cairhien**, indirectly caused a massive riot and a devastating civil war
- Made a mess in **Tear** by bringing Aiel into the citadel, fighting ancient evil, and provoking a massive Trolloc invasion
- Made a mess at **Al'cair Dal** by wrestling with the access key tied to the very powers of creation (permanent weather disruption, massive earthquake, and catastrophic social collapse)
- Made another mess in **Cairhien** by triggering a foreign invasion and near-genocidal conquest
- Made a mess in **Caemlyn** by destroying the royal palace and killing Rahvin
- Made another mess in **Cairhien** by getting the palace there blown up by assassins
- Made a mess in **Far Madding** by luring several treacherous male channelers into the city with murderous intent, getting arrested, and causing a diplomatic incident
- Made a mess in **Illian** by invading with his personal army and messily fighting Sammael
- Made a mess all over **Altara** by conducting a guerrilla magic campaign against the Seanchan military occupation and wrecking diplomatic talks
- Made a mess near **Tar Valon** by having an existential crisis that nearly destroyed the universe and also caused a bad storm

`1001 NE`
**Mess Cleaner**, Andor, the Blight

- Cleaned up some of the mess by forcing a peace alliance at the **Field of Merrilor**
- Cleaned up even more of the mess by offering his life to save the world at **Shayol Ghul**
